import { access } from "node:fs/promises";
import { constants } from "node:fs";
import { join } from "node:path";
import { getProfile } from "@/lib/profile";
import { config } from "@/bitacora.config";

async function chartExists(): Promise<boolean> {
  try {
    await access(
      join(process.cwd(), "public", "assets", "contributions.svg"),
      constants.R_OK,
    );
    return true;
  } catch {
    return false;
  }
}

/**
 * GitHub profile card on the home — avatar + handle + bio + live stats.
 * Server component: reads `public/assets/profile.json` (generated by the
 * erno-modo-sync-all skill) at request time. If the file is missing, renders
 * a minimal fallback so the home still works without external dependencies.
 */
export default async function GitHubWidget() {
  const { developer } = config;
  const [profile, hasChart] = await Promise.all([getProfile(), chartExists()]);
  const ghUrl = `https://github.com/${developer.github}`;

  const stats: string[] = [];
  if (profile) {
    if (typeof profile.publicRepos === "number") {
      stats.push(`${profile.publicRepos} repos públicos`);
    }
    if (typeof profile.followers === "number") {
      stats.push(`${profile.followers} followers`);
    }
    if (profile.contributions && typeof profile.contributions.total === "number") {
      stats.push(
        `${profile.contributions.total} contribuciones · ${profile.contributions.restricted} privadas`,
      );
    }
  }

  const bio =
    profile?.bio ??
    "Sr AI Engineer @ MODO · TypeScript · Next.js · AI-driven dev con Claude Code.";

  return (
    <section aria-labelledby="gh-widget-label" className="mb-12">
      <p
        id="gh-widget-label"
        className="mb-3 text-xs font-semibold uppercase tracking-[0.1em] text-muted"
      >
        Quién escribe
      </p>
      <article className="grid grid-cols-[auto_1fr] items-start gap-5 rounded-2xl border border-border bg-surface p-5">
        <a
          href={ghUrl}
          target="_blank"
          rel="noopener noreferrer"
          aria-label={`GitHub de ${developer.github}`}
          className="block"
        >
          {/* Avatar served by github.com; intentionally plain <img> to avoid
              remotePatterns config noise. Small + non-LCP → fine to keep here. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={profile?.avatarUrl ?? `${ghUrl}.png`}
            alt={`Avatar de ${developer.name} (@${developer.github})`}
            width={64}
            height={64}
            loading="lazy"
            className="block h-16 w-16 rounded-full border border-border"
          />
        </a>
        <div className="flex min-w-0 flex-col gap-1">
          <div className="font-display text-base font-bold tracking-tight text-ink">
            {developer.name}
          </div>
          <a
            href={ghUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="w-fit text-xs text-accent underline decoration-accent/30 underline-offset-2 transition-colors hover:decoration-accent"
          >
            @{developer.github} · GitHub
          </a>
          <p className="mt-1 text-sm leading-relaxed text-muted">{bio}</p>
          {stats.length > 0 && (
            <div className="mt-2.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted tabular-nums">
              {stats.map((s, i) => (
                <span key={s} className="inline-flex items-center gap-2">
                  {i > 0 && (
                    <span aria-hidden className="text-border">
                      ·
                    </span>
                  )}
                  {s}
                </span>
              ))}
            </div>
          )}
        </div>
        {hasChart && (
          <div className="col-span-2 mt-2 border-t border-border pt-4">
            <p className="mb-2.5 text-[11px] font-semibold uppercase tracking-[0.1em] text-muted">
              Contribuciones · último año
            </p>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/assets/contributions.svg"
              alt="Heatmap de contribuciones de @SoyErnoModo en el último año"
              loading="lazy"
              className="block h-auto w-full max-w-full"
            />
          </div>
        )}
      </article>
    </section>
  );
}
